# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
            
    steps:
    - uses: actions/checkout@v3
    - run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}
    - ${{ secrets.DEPLOY_PASSWORD }}
    - uses: nekiro/ssh-job@v1.0.5
      name: ssh-job
      
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        user: ${{ secrets.DEPLOY_USER }}
        command: mkdir test
      
    - run: echo 'I successfully done'
    
    
